# Common configuration applied to all microservices
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

# Common Okta configuration
okta:
  oauth2:
    issuer: https://trial-5890863.okta.com/oauth2/default
    audience: api://default

# Common OAuth2 Resource Server config
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://trial-5890863.okta.com/oauth2/default

# Common Management/Actuator config
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
